### ISSUE TITLE
The songs list is way too long. 

### ISSUE THREAD

**Issue by MorgansPlayGames** [MorgansPlayGames/music-by-theme#14]
Getting a huge list in the page makes the whole page way too long 

It makes accessing the lower part of the page with an active search difficult. 

We need to shorten the get parameters, or make a model for the list to fit into.

**Comment by jwickster** [comment]
Look at truncating results -OR- have a drop down of 5, 10, 15 limit results

**Comment by MorgansPlayGames** [comment]
Modal Bootstrap solved this one!
